Search.appendIndex(
    [
                {
            "fqsen": "\\TodoList\\Config\\Config",
            "name": "Config",
            "summary": "Application\u0020configuration.",
            "url": "classes/TodoList-Config-Config.html"
        },                {
            "fqsen": "\\TodoList\\Config\\Config\u003A\u003AgetConfig\u0028\u0029",
            "name": "getConfig",
            "summary": "",
            "url": "classes/TodoList-Config-Config.html#method_getConfig"
        },                {
            "fqsen": "\\TodoList\\Config\\Config\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "",
            "url": "classes/TodoList-Config-Config.html#method_getData"
        },                {
            "fqsen": "\\TodoList\\Config\\Config\u003A\u003A\u0024DATA",
            "name": "DATA",
            "summary": "",
            "url": "classes/TodoList-Config-Config.html#property_DATA"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao",
            "name": "TodoDao",
            "summary": "DAO\u0020for\u0020\u007B\u0040link\u0020\\TodoList\\Model\\Todo\u007D.",
            "url": "classes/TodoList-Dao-TodoDao.html"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method___destruct"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Find\u0020all\u0020\u007B\u0040link\u0020Todo\u007Ds\u0020by\u0020search\u0020criteria.",
            "url": "classes/TodoList-Dao-TodoDao.html#method_find"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Find\u0020\u007B\u0040link\u0020Todo\u007D\u0020by\u0020identifier.",
            "url": "classes/TodoList-Dao-TodoDao.html#method_findById"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Save\u0020\u007B\u0040link\u0020Todo\u007D.",
            "url": "classes/TodoList-Dao-TodoDao.html#method_save"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020\u007B\u0040link\u0020Todo\u007D\u0020by\u0020identifier.",
            "url": "classes/TodoList-Dao-TodoDao.html#method_delete"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AgetDb\u0028\u0029",
            "name": "getDb",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_getDb"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AgetFindSql\u0028\u0029",
            "name": "getFindSql",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_getFindSql"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_insert"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_update"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_execute"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AgetParams\u0028\u0029",
            "name": "getParams",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_getParams"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AexecuteStatement\u0028\u0029",
            "name": "executeStatement",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_executeStatement"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_query"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AthrowDbError\u0028\u0029",
            "name": "throwDbError",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_throwDbError"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AformatDateTime\u0028\u0029",
            "name": "formatDateTime",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_formatDateTime"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003AformatBoolean\u0028\u0029",
            "name": "formatBoolean",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#method_formatBoolean"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoDao\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoDao.html#property_db"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoSearchCriteria",
            "name": "TodoSearchCriteria",
            "summary": "Search\u0020criteria\u0020for\u0020\u007B\u0040link\u0020TodoDao\u007D.",
            "url": "classes/TodoList-Dao-TodoSearchCriteria.html"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoSearchCriteria\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoSearchCriteria.html#method_getStatus"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoSearchCriteria\u003A\u003AsetStatus\u0028\u0029",
            "name": "setStatus",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoSearchCriteria.html#method_setStatus"
        },                {
            "fqsen": "\\TodoList\\Dao\\TodoSearchCriteria\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/TodoList-Dao-TodoSearchCriteria.html#property_status"
        },                {
            "fqsen": "\\TodoList\\Exception\\NotFoundException",
            "name": "NotFoundException",
            "summary": "Exception\u0020which\u0020causes\u0020HTTP\u0020ERROR\u0020404\u0020\u0028Not\u0020Found\u0029.",
            "url": "classes/TodoList-Exception-NotFoundException.html"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash",
            "name": "Flash",
            "summary": "Class\u0020managing\u0020flash\u0020messages.",
            "url": "classes/TodoList-Flash-Flash.html"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/TodoList-Flash-Flash.html#method___construct"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash\u003A\u003AhasFlashes\u0028\u0029",
            "name": "hasFlashes",
            "summary": "",
            "url": "classes/TodoList-Flash-Flash.html#method_hasFlashes"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash\u003A\u003AaddFlash\u0028\u0029",
            "name": "addFlash",
            "summary": "",
            "url": "classes/TodoList-Flash-Flash.html#method_addFlash"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash\u003A\u003AgetFlashes\u0028\u0029",
            "name": "getFlashes",
            "summary": "Get\u0020flash\u0020messages\u0020and\u0020clear\u0020them.",
            "url": "classes/TodoList-Flash-Flash.html#method_getFlashes"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash\u003A\u003AinitFlashes\u0028\u0029",
            "name": "initFlashes",
            "summary": "",
            "url": "classes/TodoList-Flash-Flash.html#method_initFlashes"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash\u003A\u003AFLASHES_KEY",
            "name": "FLASHES_KEY",
            "summary": "",
            "url": "classes/TodoList-Flash-Flash.html#constant_FLASHES_KEY"
        },                {
            "fqsen": "\\TodoList\\Flash\\Flash\u003A\u003A\u0024flashes",
            "name": "flashes",
            "summary": "",
            "url": "classes/TodoList-Flash-Flash.html#property_flashes"
        },                {
            "fqsen": "\\TodoList\\Mapping\\TodoMapper",
            "name": "TodoMapper",
            "summary": "Mapper\u0020for\u0020\u007B\u0040link\u0020\\TodoList\\Model\\Todo\u007D\u0020from\u0020array.",
            "url": "classes/TodoList-Mapping-TodoMapper.html"
        },                {
            "fqsen": "\\TodoList\\Mapping\\TodoMapper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/TodoList-Mapping-TodoMapper.html#method___construct"
        },                {
            "fqsen": "\\TodoList\\Mapping\\TodoMapper\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "Maps\u0020array\u0020to\u0020the\u0020given\u0020\u007B\u0040link\u0020Todo\u007D.",
            "url": "classes/TodoList-Mapping-TodoMapper.html#method_map"
        },                {
            "fqsen": "\\TodoList\\Mapping\\TodoMapper\u003A\u003AcreateDateTime\u0028\u0029",
            "name": "createDateTime",
            "summary": "",
            "url": "classes/TodoList-Mapping-TodoMapper.html#method_createDateTime"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo",
            "name": "Todo",
            "summary": "Model\u0020class\u0020representing\u0020one\u0020TODO\u0020item.",
            "url": "classes/TodoList-Model-Todo.html"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020new\u0020\u007B\u0040link\u0020Todo\u007D\u0020with\u0020default\u0020properties\u0020set.",
            "url": "classes/TodoList-Model-Todo.html#method___construct"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AallStatuses\u0028\u0029",
            "name": "allStatuses",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_allStatuses"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AallPriorities\u0028\u0029",
            "name": "allPriorities",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_allPriorities"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getId"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setId"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetPriority\u0028\u0029",
            "name": "getPriority",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getPriority"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetPriority\u0028\u0029",
            "name": "setPriority",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setPriority"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetCreatedOn\u0028\u0029",
            "name": "getCreatedOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getCreatedOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetCreatedOn\u0028\u0029",
            "name": "setCreatedOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setCreatedOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetDueOn\u0028\u0029",
            "name": "getDueOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getDueOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetDueOn\u0028\u0029",
            "name": "setDueOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setDueOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetLastModifiedOn\u0028\u0029",
            "name": "getLastModifiedOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getLastModifiedOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetLastModifiedOn\u0028\u0029",
            "name": "setLastModifiedOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setLastModifiedOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getTitle"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setTitle"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getDescription"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setDescription"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetComment\u0028\u0029",
            "name": "getComment",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getComment"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetComment\u0028\u0029",
            "name": "setComment",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setComment"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getStatus"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetStatus\u0028\u0029",
            "name": "setStatus",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setStatus"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AgetDeleted\u0028\u0029",
            "name": "getDeleted",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_getDeleted"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003AsetDeleted\u0028\u0029",
            "name": "setDeleted",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#method_setDeleted"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003APRIORITY_HIGH",
            "name": "PRIORITY_HIGH",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#constant_PRIORITY_HIGH"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003APRIORITY_MEDIUM",
            "name": "PRIORITY_MEDIUM",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#constant_PRIORITY_MEDIUM"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003APRIORITY_LOW",
            "name": "PRIORITY_LOW",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#constant_PRIORITY_LOW"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003ASTATUS_PENDING",
            "name": "STATUS_PENDING",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#constant_STATUS_PENDING"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003ASTATUS_DONE",
            "name": "STATUS_DONE",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#constant_STATUS_DONE"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003ASTATUS_VOIDED",
            "name": "STATUS_VOIDED",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#constant_STATUS_VOIDED"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_id"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024priority",
            "name": "priority",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_priority"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024createdOn",
            "name": "createdOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_createdOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024dueOn",
            "name": "dueOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_dueOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024lastModifiedOn",
            "name": "lastModifiedOn",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_lastModifiedOn"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_title"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_description"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024comment",
            "name": "comment",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_comment"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_status"
        },                {
            "fqsen": "\\TodoList\\Model\\Todo\u003A\u003A\u0024deleted",
            "name": "deleted",
            "summary": "",
            "url": "classes/TodoList-Model-Todo.html#property_deleted"
        },                {
            "fqsen": "\\TodoList\\error_field\u0028\u0029",
            "name": "error_field",
            "summary": "",
            "url": "namespaces/todolist.html#function_error_field"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils",
            "name": "Utils",
            "summary": "Miscellaneous\u0020utility\u0020methods.",
            "url": "classes/TodoList-Util-Utils.html"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/TodoList-Util-Utils.html#method___construct"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003AcreateLink\u0028\u0029",
            "name": "createLink",
            "summary": "Generate\u0020link.",
            "url": "classes/TodoList-Util-Utils.html#method_createLink"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003AformatDate\u0028\u0029",
            "name": "formatDate",
            "summary": "Format\u0020date.",
            "url": "classes/TodoList-Util-Utils.html#method_formatDate"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003AformatDateTime\u0028\u0029",
            "name": "formatDateTime",
            "summary": "Format\u0020date\u0020and\u0020time.",
            "url": "classes/TodoList-Util-Utils.html#method_formatDateTime"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003AiconStatus\u0028\u0029",
            "name": "iconStatus",
            "summary": "Returns\u0020icon\u0020for\u0020status.",
            "url": "classes/TodoList-Util-Utils.html#method_iconStatus"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003AiconPriority\u0028\u0029",
            "name": "iconPriority",
            "summary": "Returns\u0020icon\u0020for\u0020priority.",
            "url": "classes/TodoList-Util-Utils.html#method_iconPriority"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "Redirect\u0020to\u0020the\u0020given\u0020page.",
            "url": "classes/TodoList-Util-Utils.html#method_redirect"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003AgetUrlParam\u0028\u0029",
            "name": "getUrlParam",
            "summary": "Get\u0020value\u0020of\u0020the\u0020URL\u0020param.",
            "url": "classes/TodoList-Util-Utils.html#method_getUrlParam"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003AgetTodoByGetId\u0028\u0029",
            "name": "getTodoByGetId",
            "summary": "Get\u0020\u007B\u0040link\u0020Todo\u007D\u0020by\u0020the\u0020identifier\u0020\u0027id\u0027\u0020found\u0020in\u0020the\u0020URL.",
            "url": "classes/TodoList-Util-Utils.html#method_getTodoByGetId"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003Acapitalize\u0028\u0029",
            "name": "capitalize",
            "summary": "Capitalize\u0020the\u0020first\u0020letter\u0020of\u0020the\u0020given\u0020string",
            "url": "classes/TodoList-Util-Utils.html#method_capitalize"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003Aescape\u0028\u0029",
            "name": "escape",
            "summary": "Escape\u0020the\u0020given\u0020string",
            "url": "classes/TodoList-Util-Utils.html#method_escape"
        },                {
            "fqsen": "\\TodoList\\Util\\Utils\u003A\u003A\u0024STATUS_ICONS",
            "name": "STATUS_ICONS",
            "summary": "",
            "url": "classes/TodoList-Util-Utils.html#property_STATUS_ICONS"
        },                {
            "fqsen": "\\TodoList\\Validation\\TodoValidator",
            "name": "TodoValidator",
            "summary": "Validator\u0020for\u0020\u007B\u0040link\u0020\\TodoList\\Model\\Todo\u007D.",
            "url": "classes/TodoList-Validation-TodoValidator.html"
        },                {
            "fqsen": "\\TodoList\\Validation\\TodoValidator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/TodoList-Validation-TodoValidator.html#method___construct"
        },                {
            "fqsen": "\\TodoList\\Validation\\TodoValidator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate\u0020the\u0020given\u0020\u007B\u0040link\u0020Todo\u007D\u0020instance.",
            "url": "classes/TodoList-Validation-TodoValidator.html#method_validate"
        },                {
            "fqsen": "\\TodoList\\Validation\\TodoValidator\u003A\u003AvalidateStatus\u0028\u0029",
            "name": "validateStatus",
            "summary": "Validate\u0020the\u0020given\u0020status.",
            "url": "classes/TodoList-Validation-TodoValidator.html#method_validateStatus"
        },                {
            "fqsen": "\\TodoList\\Validation\\TodoValidator\u003A\u003AvalidatePriority\u0028\u0029",
            "name": "validatePriority",
            "summary": "Validate\u0020the\u0020given\u0020priority.",
            "url": "classes/TodoList-Validation-TodoValidator.html#method_validatePriority"
        },                {
            "fqsen": "\\TodoList\\Validation\\TodoValidator\u003A\u003AisValidStatus\u0028\u0029",
            "name": "isValidStatus",
            "summary": "",
            "url": "classes/TodoList-Validation-TodoValidator.html#method_isValidStatus"
        },                {
            "fqsen": "\\TodoList\\Validation\\TodoValidator\u003A\u003AisValidPriority\u0028\u0029",
            "name": "isValidPriority",
            "summary": "",
            "url": "classes/TodoList-Validation-TodoValidator.html#method_isValidPriority"
        },                {
            "fqsen": "\\TodoList\\Validation\\ValidationError",
            "name": "ValidationError",
            "summary": "Validation\u0020error.",
            "url": "classes/TodoList-Validation-ValidationError.html"
        },                {
            "fqsen": "\\TodoList\\Validation\\ValidationError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020new\u0020validation\u0020error.",
            "url": "classes/TodoList-Validation-ValidationError.html#method___construct"
        },                {
            "fqsen": "\\TodoList\\Validation\\ValidationError\u003A\u003AgetSource\u0028\u0029",
            "name": "getSource",
            "summary": "Get\u0020source\u0020of\u0020the\u0020error.",
            "url": "classes/TodoList-Validation-ValidationError.html#method_getSource"
        },                {
            "fqsen": "\\TodoList\\Validation\\ValidationError\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "Get\u0020error\u0020message.",
            "url": "classes/TodoList-Validation-ValidationError.html#method_getMessage"
        },                {
            "fqsen": "\\TodoList\\Validation\\ValidationError\u003A\u003A\u0024source",
            "name": "source",
            "summary": "",
            "url": "classes/TodoList-Validation-ValidationError.html#property_source"
        },                {
            "fqsen": "\\TodoList\\Validation\\ValidationError\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/TodoList-Validation-ValidationError.html#property_message"
        },                {
            "fqsen": "\\TodoList\\Index",
            "name": "Index",
            "summary": "Main\u0020application\u0020class.",
            "url": "classes/TodoList-Index.html"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "System\u0020config.",
            "url": "classes/TodoList-Index.html#method_init"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020application\u0021",
            "url": "classes/TodoList-Index.html#method_run"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AhandleException\u0028\u0029",
            "name": "handleException",
            "summary": "Exception\u0020handler.",
            "url": "classes/TodoList-Index.html#method_handleException"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AloadClass\u0028\u0029",
            "name": "loadClass",
            "summary": "Class\u0020loader.",
            "url": "classes/TodoList-Index.html#method_loadClass"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AgetPage\u0028\u0029",
            "name": "getPage",
            "summary": "",
            "url": "classes/TodoList-Index.html#method_getPage"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AcheckPage\u0028\u0029",
            "name": "checkPage",
            "summary": "",
            "url": "classes/TodoList-Index.html#method_checkPage"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003ArunPage\u0028\u0029",
            "name": "runPage",
            "summary": "",
            "url": "classes/TodoList-Index.html#method_runPage"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AgetScript\u0028\u0029",
            "name": "getScript",
            "summary": "",
            "url": "classes/TodoList-Index.html#method_getScript"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AgetTemplate\u0028\u0029",
            "name": "getTemplate",
            "summary": "",
            "url": "classes/TodoList-Index.html#method_getTemplate"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AhasScript\u0028\u0029",
            "name": "hasScript",
            "summary": "",
            "url": "classes/TodoList-Index.html#method_hasScript"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003AhasTemplate\u0028\u0029",
            "name": "hasTemplate",
            "summary": "",
            "url": "classes/TodoList-Index.html#method_hasTemplate"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003ADEFAULT_PAGE",
            "name": "DEFAULT_PAGE",
            "summary": "",
            "url": "classes/TodoList-Index.html#constant_DEFAULT_PAGE"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003APAGE_DIR",
            "name": "PAGE_DIR",
            "summary": "",
            "url": "classes/TodoList-Index.html#constant_PAGE_DIR"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003ALAYOUT_DIR",
            "name": "LAYOUT_DIR",
            "summary": "",
            "url": "classes/TodoList-Index.html#constant_LAYOUT_DIR"
        },                {
            "fqsen": "\\TodoList\\Index\u003A\u003A\u0024CLASSES",
            "name": "CLASSES",
            "summary": "",
            "url": "classes/TodoList-Index.html#property_CLASSES"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\TodoList\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/todolist-config.html"
        },                {
            "fqsen": "\\TodoList\\Dao",
            "name": "Dao",
            "summary": "",
            "url": "namespaces/todolist-dao.html"
        },                {
            "fqsen": "\\TodoList\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/todolist-exception.html"
        },                {
            "fqsen": "\\TodoList\\Flash",
            "name": "Flash",
            "summary": "",
            "url": "namespaces/todolist-flash.html"
        },                {
            "fqsen": "\\TodoList",
            "name": "TodoList",
            "summary": "",
            "url": "namespaces/todolist.html"
        },                {
            "fqsen": "\\TodoList\\Mapping",
            "name": "Mapping",
            "summary": "",
            "url": "namespaces/todolist-mapping.html"
        },                {
            "fqsen": "\\TodoList\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/todolist-model.html"
        },                {
            "fqsen": "\\TodoList\\Util",
            "name": "Util",
            "summary": "",
            "url": "namespaces/todolist-util.html"
        },                {
            "fqsen": "\\TodoList\\Validation",
            "name": "Validation",
            "summary": "",
            "url": "namespaces/todolist-validation.html"
        }            ]
);
